### PR TITLE
markdown component for parsing markdown text

### LINKED ISSUE #56: services descriptions should be parsed with markdown
I've just added more detailed descriptions of each service and this lack is shown pretty clearly now.

### PR DESCRIPTION
**Pull request by jennschiffer**
closes #56 

this uses the marked module, just like in current nest and also this tutorial - https://facebook.github.io/react/docs/tutorial.html

in the tutorial they mention the prop type "dangerouslySetInnerHTML" that has to be used (https://facebook.github.io/react/tips/dangerously-set-inner-html.html) which I had to change the flag in eslint to allow. 

As this method was used in a canonical react tutorial, I used it here. #livedangerously

### CODE REVIEW

**Comment by tkellen** [comment]
:+1:!

**Comment by tkellen** [comment]
This should have been rebased with `--autosquash`. No need to change it now, just pointing out this was missed.

**Comment by jennschiffer** [comment]
thanks for the tip!

**Comment by tkellen** [comment]
Sure thing!

**Pull request merged**
