### PR TITLE
Minor refactor.

### PR DESCRIPTION
**Pull request by cowboy**
* Use functional react components wherever possible
* Rename BaseComponent -> BoundComponent
* Added propTypes where missing

### CODE REVIEW

**Comment by tkellen** [comment]
heck yes. destroy all classes!

**Comment by jennschiffer** [comment]
what is your motivation for now deciding to use react's componentClass instead of es6?

**Comment by cowboy** [comment]
@jennschiffer I don't understand. Where am I not using ES6?

**Comment by jennschiffer** [comment]
i mean the canon es6 classes. now we are using React.createClass. i was wondering what made one better in our situation than the other

**Comment by cowboy** [comment]
I'm using the new "stateless functional component" syntax instead of full-on classes for components that only take `props` and render without any additional code:

https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components

**Comment by jennschiffer** [comment]
:+1:

**Pull request merged**
